title: Dr Krzysztof Orzeł # your name (or website title) here
logo: "/images/kz2020medium.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  10+ years of Microwave Engineering and Data Analyst know-how combined with extensive international experience. Posses Diplom-Ingenieur degree from Karlsruhe Institute of Technology in Electrical Engineering and a PhD degree from the University of Massachusetts in Remote Sensing. 
  <br><br>
  <a href="https://www.linkedin.com/in/orzelk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-165369844-1 # your Google Analytics tracking ID here
