title: Dr Krzysztof Orzeł # your name (or website title) here
logo: "/images/kz2020cirle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  10+ years of Microwave Engineering and Data Analyst know-how combined with and extesive international experience. Posses Diplom-Ingenieur degree from Karlsruhe Institue of Technology in Electrical Enginnering and PhD degree from University of Massachusetts in Remote Sensing. 
  <br><br>
  <a href="https://www.linkedin.com/in/orzelk/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
